name: adam_company_consumer_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.12.2
  dio: ^3.0.10
  intl: ^0.16.1
  shimmer: ^1.1.2
  share: ^0.6.5+2
  geocoding: ^1.0.5
  geolocator: ^6.1.0
  provider: ^4.3.2+2
  rect_getter: ^0.1.0
  fluttertoast: ^7.1.1
  google_fonts: ^1.1.0
  connectivity: ^2.0.1
  flutter_html: ^1.0.2
  apple_sign_in: ^0.1.0
  image_cropper: ^1.3.1
  url_launcher: ^5.7.10
  google_sign_in: ^4.5.4
  rflutter_alert: ^1.1.0
  device_preview: ^0.4.8
  stripe_payment: ^1.0.8
  carousel_slider: ^2.3.1
  pin_code_fields: ^5.2.0
  image_picker: ^0.6.7+11
  loading_animations: ^2.1.0
  charts_flutter: ^0.9.0
  percent_indicator: ^2.1.8
  flutter_spinkit: ^4.1.2+1
  flutter_credit_card: ^0.1.3
  firebase_messaging: ^7.0.3
  draggable_scrollbar: ^0.0.4
  shared_preferences: ^0.5.12
  google_maps_flutter: ^1.0.6
  flutter_rating_bar: ^3.0.1+1
  flutter_launcher_icons: ^0.8.1
#  flutter_polyline_points: ^0.2.4
  flutter_image_compress: ^0.7.0
  flutter_facebook_login: ^3.0.0
  flutter_datetime_picker: ^1.4.0
#  google_maps_place_picker: ^1.0.0
  google_map_location_picker: ^4.0.0
  persistent_bottom_nav_bar: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_launcher.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/reward/
